### ISSUE TITLE
ザラ場中にも買いを入れられるようにする

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/yutai#1]
現在は取引時間外に成行でのみ一般売り注文を入れるようなシステムになっているが、SMBC日興証券はザラ場中にも一般売りの在庫が補充されることがある。
そのため、取引時間中にも注文を入れられるように修正を行う。
ただし、成行で注文を入れると即約定してしまうため、値幅上限で注文を入れることとする。

**Comment by poi-ai** [comment]
24/9/23( #21edaa4 )と25/2のコミットで対応済。値幅の上限の計算が必要なため、steal実行時間外に終値を取得して翌日のS高を計算するスクリプトも併せて作成

**Comment by poi-ai** [comment]
7時台にsrc/owarine.py を実行して、owarine.csvに終値と翌営業日の高値を計算して記録
src/steal.pyでの8時以降の動作はこのowarine.csvに記録した値を基に注文を発注する形で

**Comment by poi-ai** [comment]
株価が4桁の場合に1,000 のように,がの混ざった記述をfloat扱いしようとしてエラーで落ちたケースがあったので、そこだけ直してテストはOK。
またバグが出たら新しいissueで対応

**Comment by poi-ai** [comment]
```
Traceback (most recent call last):
  File "/home/yutai/src/owarine.py", line 68, in <module>
    owarine.main()
  File "/home/yutai/src/owarine.py", line 53, in main
    upper_price = self.culc.culc_upper_price(stock_code, float(owarine_info[0]))
ValueError: could not convert string to float: '1,893'
```

株価が4桁以上の場合に,が混ざった記述をfloat扱いしようとしてエラーで落ちたケースがあったので修正
またバグが出たら新しいissueで対応
