### ISSUE TITLE
優待補完情報メッセージ生成でエラー

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/yutai#2]
カブコムで一般在庫の取得・通知を行う場合に、取得対象の優待補完情報がない場合にログにひたすらエラーが出続けるのを直したい

```
2024-09-21 20:20:18,235 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 1952
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,236 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 2001
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,237 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 2201
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,240 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 2810
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,246 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 3738
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,248 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 4008
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,250 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 4540
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
2024-09-21 20:20:18,252 (2800)  [ERROR] 優待補完情報メッセージ作成処理でエラー 証券コード: 6339
single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/home/yutai/src/main.py", line 622, in create_stock_info_message
    if not pd.isna(stock_row['通常最低保有株数'].iloc[0]):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
 [main.py in 641]
```

**Comment by poi-ai** [comment]
補完情報は人力で作らなければいかず、毎月作っていくのは無駄な手間なので削除(正確にはコメントアウト)で対応
どっかから自動で引っ張ってこれるようになったら再度送るようにする
